name: Building Docker Image

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          mvn package
      - name: Login on Docker
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container
        run: |
          docker build -t frontend/container:0.0.1 .
      - name: Push Container
        run: |
          docker push frontend/container
